apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-api 
  name: user-api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: user-api
