apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - image: abirdatta/user-api:dev
          name: user-api
          env:
          - name: DATABASE_HOST
            value: mysql
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_NAME
            value: "mydb"
          - name: DATABASE_USER
            value: "myuser"
          - name: DATABASE_PASSWORD
            value: "mysql"
          ports:
            - containerPort: 8080
              name: user-api
