apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-api 
  name: user-api
spec:
  type: LoadBalancer
  ports:
    - name: app-api-port
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: app-management-port
      port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    app: user-api
