name: Abir
spring: 
  datasource:
    url: jdbc:mysql://${DATABASE}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
spring.jpa.show-sql: true
logging: 
  file: /logs/user-service.log
  level: 
    com.ad.platform: DEBUG
    org.hibernate: ERROR
